groups:
  - name: reboot
    rules:
      - alert: NodeRebooted
        expr: rate(node_boot_time_seconds[5m]) > 0
        for: 0m
        labels:
          severity: page
        annotations:
          summary: "Machine rebooted (instance {{ $labels.instance }})"
          description: "Machine {{ $labels.instance }} has been rebooted."

      - alert: NodeRebootsTooOften
        expr: changes(node_boot_time_seconds{job="node"}[1h]) > 1
        for: 0m
        labels:
          severity: page
        annotations:
          summary: "Machine rebooted too often (instance {{ $labels.instance }})"
          description: "Machine {{ $labels.instance }} has been rebooted too often."
