version: '3'
services:
    mariadb:
        container_name: mariadb
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file: .env
        expose:
           - 3306:3306
        networks:
            - inception
        volumes:
            - mariadb:/var/lib/mysql
        restart: unless-stopped #always restarts unless we use the command stop to stop it
    nginx:
        container_name: nginx
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        depends_on:
            - wordpress
        env_file: .env
        ports:
            - 443:443 #Port that we expose on the local machine
        networks:
            - inception
        volumes:
            - wordpress:/var/www/wordpress
        restart: on-failure #This container will restart if it exists with non-zero exit status
    wordpress:
        container_name: wordpress
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
            - mariadb
        env_file: .env
        expose:
            - 9000:9000
        networks:
            - inception
        volumes:
            - wordpress:/var/www/wordpress
        restart: on-failure
volumes:
    wordpress:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PWD}/app
    mariadb:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${PWD}/app
networks:
    inception:
      name: inception
      driver: bridge












