# Generated by Django 5.0 on 2023-12-30 15:13

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile_image',
            field=models.ImageField(blank=True, default=user.models.get_default_profile_image, max_length=500, null=True, upload_to=user.models.get_profile_image_filepath),
        ),
    ]
